services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerceapp
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 
      - ./db_building:/var/lib
    networks:
      - node
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 10s
  web:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - node
    environment:
      - DATABASE_NAME=ecommerceapp
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
    

networks:
  node:
    driver: bridge