services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    networks:
      - node
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerceapp
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 
    networks:
      - node

networks:
  node:
    driver: bridge