name: Continuous integration

on: 
  push:
    branches: [workflows]
  pull_request:
    branches: [main]

jobs: 
  testRunning:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [23.x]
    steps:
      - name: 'Install mysql and setup database'
        run: sudo /etc/init.d/mysql start
        run: sudo mysql -e 'CREATE DATABASE ecommerceapp;', -uroot -proot
        run: sudo mysql -uroot -proot ecommerceapp < ./db_building/ecommerceapp.sql
      - name: 'Create .env file'
        run: |
          touch .env
          echo "DATABASE_NAME = 'ecommerceapp'" >> .env
          echo "DATABASE_USERNAME = 'root'" >> .env
          echo "DATABASE_PASSWORD = ''" >> .env
          echo "DATABASE_HOST = '127.0.0.1' >> .env
          ls -la
          cat .env
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test
